export const businessesSeed = [
  {
    name: "Accra Kitchen",
    category: "Food & Drink",
    description:
      "Authentic Ghanaian cuisine in the heart of Brixton. From jollof rice to kelewele, we bring the flavours of Accra to South London.",
    location: "Brixton, London",
    image: "gradient-food",
    rating: 4.8,
    featured: true,
    contactPhone: "+44 20 7946 0001",
    contactEmail: "info@accrakitchen.co.uk",
    website: "https://accrakitchen.co.uk",
  },
  {
    name: "Asante Legal Partners",
    category: "Legal",
    description:
      "Specialist immigration and family law solicitors serving the Ghanaian community. Expert advice on visas, citizenship, and settlement.",
    location: "Tottenham, London",
    image: "gradient-legal",
    rating: 4.9,
    featured: true,
    contactPhone: "+44 20 7946 0002",
    contactEmail: "contact@asantelegal.co.uk",
    website: "https://asantelegal.co.uk",
  },
  {
    name: "Kumasi Cuts Barbershop",
    category: "Beauty",
    description:
      "Premium barbershop specialising in African hair styling for men and boys. Fades, lineups, and traditional styles.",
    location: "Peckham, London",
    image: "gradient-beauty",
    rating: 4.7,
    featured: false,
    contactPhone: "+44 20 7946 0003",
    contactEmail: "bookings@kumasicuts.co.uk",
    website: "https://kumasicuts.co.uk",
  },
  {
    name: "GoldCoast Express Logistics",
    category: "Transport",
    description:
      "Reliable shipping and logistics between the UK and Ghana. Door-to-door parcel delivery, cargo, and freight forwarding.",
    location: "Croydon, London",
    image: "gradient-transport",
    rating: 4.6,
    featured: true,
    contactPhone: "+44 20 7946 0004",
    contactEmail: "ship@goldcoastexpress.co.uk",
    website: "https://goldcoastexpress.co.uk",
  },
  {
    name: "Adinkra Financial Services",
    category: "Finance",
    description:
      "Financial planning, tax advisory, and money transfer services tailored for the Ghanaian diaspora. Helping you build wealth across borders.",
    location: "Stratford, London",
    image: "gradient-finance",
    rating: 4.8,
    featured: false,
    contactPhone: "+44 20 7946 0005",
    contactEmail: "advice@adinkrafinancial.co.uk",
    website: "https://adinkrafinancial.co.uk",
  },
  {
    name: "TechGhana Ltd",
    category: "Technology",
    description:
      "IT consultancy and software development firm founded by Ghanaian tech professionals. Web development, mobile apps, and digital transformation.",
    location: "Shoreditch, London",
    image: "gradient-tech",
    rating: 4.9,
    featured: true,
    contactPhone: "+44 20 7946 0006",
    contactEmail: "hello@techghana.co.uk",
    website: "https://techghana.co.uk",
  },
  {
    name: "Nana's Beauty Lounge",
    category: "Beauty",
    description:
      "Full-service beauty salon offering braids, locs, weaves, and natural hair care. Specialising in African and Caribbean styles.",
    location: "Lewisham, London",
    image: "gradient-beauty",
    rating: 4.6,
    featured: false,
    contactPhone: "+44 20 7946 0007",
    contactEmail: "book@nanasbeauty.co.uk",
    website: "https://nanasbeauty.co.uk",
  },
  {
    name: "Osu Market Foods",
    category: "Food & Drink",
    description:
      "Your one-stop shop for Ghanaian groceries and ingredients. Fresh yams, plantains, spices, and imported goods direct from Ghana.",
    location: "Dalston, London",
    image: "gradient-food",
    rating: 4.5,
    featured: false,
    contactPhone: "+44 20 7946 0008",
    contactEmail: "orders@osumarketfoods.co.uk",
    website: "https://osumarketfoods.co.uk",
  },
  {
    name: "Cape Coast Properties",
    category: "Finance",
    description:
      "Property investment and management services for Ghanaians in the UK. Buy, sell, or rent properties in London and across Ghana.",
    location: "Canary Wharf, London",
    image: "gradient-finance",
    rating: 4.7,
    featured: false,
    contactPhone: "+44 20 7946 0009",
    contactEmail: "info@capecoastproperties.co.uk",
    website: "https://capecoastproperties.co.uk",
  },
  {
    name: "Kwaku Health & Wellness",
    category: "Health",
    description:
      "Holistic health centre offering physiotherapy, nutrition advice, and wellness programmes. Culturally sensitive care for the African community.",
    location: "Hackney, London",
    image: "gradient-health",
    rating: 4.8,
    featured: false,
    contactPhone: "+44 20 7946 0010",
    contactEmail: "care@kwakuhealth.co.uk",
    website: "https://kwakuhealth.co.uk",
  },
  {
    name: "Sankofa Education Hub",
    category: "Education",
    description:
      "Tutoring and mentoring centre for young Ghanaians. GCSE and A-Level support, university applications, and career guidance.",
    location: "Woolwich, London",
    image: "gradient-education",
    rating: 4.9,
    featured: false,
    contactPhone: "+44 20 7946 0011",
    contactEmail: "learn@sankofaeducation.co.uk",
    website: "https://sankofaeducation.co.uk",
  },
  {
    name: "Elmina Travel & Tours",
    category: "Transport",
    description:
      "Travel agency specialising in flights to Ghana, heritage tours, and holiday packages. Best rates on Accra and Kumasi flights.",
    location: "Seven Sisters, London",
    image: "gradient-transport",
    rating: 4.5,
    featured: false,
    contactPhone: "+44 20 7946 0012",
    contactEmail: "travel@elminatours.co.uk",
    website: "https://elminatours.co.uk",
  },
  {
    name: "Kejetia Fashion House",
    category: "Beauty",
    description:
      "Bespoke African fashion and textiles. Traditional kente cloth, modern Ankara designs, and custom tailoring for all occasions.",
    location: "Brixton, London",
    image: "gradient-beauty",
    rating: 4.7,
    featured: false,
    contactPhone: "+44 20 7946 0013",
    contactEmail: "style@kejetiafashion.co.uk",
    website: "https://kejetiafashion.co.uk",
  },
  {
    name: "Ho Chop Bar",
    category: "Food & Drink",
    description:
      "Casual Ghanaian eatery serving banku, fufu, waakye, and other local favourites. Taste the Volta Region in East London.",
    location: "Barking, London",
    image: "gradient-food",
    rating: 4.4,
    featured: false,
    contactPhone: "+44 20 7946 0014",
    contactEmail: "eat@hochopbar.co.uk",
    website: "https://hochopbar.co.uk",
  },
  {
    name: "Ashesi Insurance Brokers",
    category: "Finance",
    description:
      "Independent insurance brokers offering home, motor, life, and travel insurance. Competitive quotes and personalised service.",
    location: "Elephant & Castle, London",
    image: "gradient-finance",
    rating: 4.6,
    featured: false,
    contactPhone: "+44 20 7946 0015",
    contactEmail: "quote@ashesiinsurance.co.uk",
    website: "https://ashesiinsurance.co.uk",
  },
  {
    name: "Tema Auto Services",
    category: "Transport",
    description:
      "MOT, servicing, and repairs for all vehicle makes. Trusted by the Ghanaian community for honest and affordable car maintenance.",
    location: "Catford, London",
    image: "gradient-transport",
    rating: 4.5,
    featured: false,
    contactPhone: "+44 20 7946 0016",
    contactEmail: "service@temaauto.co.uk",
    website: "https://temaauto.co.uk",
  },
  {
    name: "Labadi Events & Decor",
    category: "Food & Drink",
    description:
      "Event planning and decoration services for weddings, naming ceremonies, and parties. Bringing Ghanaian elegance to your celebrations.",
    location: "Edmonton, London",
    image: "gradient-food",
    rating: 4.8,
    featured: false,
    contactPhone: "+44 20 7946 0017",
    contactEmail: "events@labadievents.co.uk",
    website: "https://labadievents.co.uk",
  },
  {
    name: "Koforidua Media Group",
    category: "Technology",
    description:
      "Digital marketing, videography, and content creation agency. Helping Ghanaian businesses grow their online presence in the UK.",
    location: "Camden, London",
    image: "gradient-tech",
    rating: 4.7,
    featured: false,
    contactPhone: "+44 20 7946 0018",
    contactEmail: "create@koforiduamedia.co.uk",
    website: "https://koforiduamedia.co.uk",
  },
  {
    name: "Volta Cleaning Services",
    category: "Health",
    description:
      "Professional cleaning services for homes and offices. Deep cleaning, end-of-tenancy, and regular maintenance contracts available.",
    location: "Walthamstow, London",
    image: "gradient-health",
    rating: 4.4,
    featured: false,
    contactPhone: "+44 20 7946 0019",
    contactEmail: "clean@voltacleaning.co.uk",
    website: "https://voltacleaning.co.uk",
  },
  {
    name: "Dzorwulu Pharmacy",
    category: "Health",
    description:
      "Community pharmacy offering prescriptions, health advice, and wellness products. Multilingual staff speaking English, Twi, and Ga.",
    location: "Tottenham, London",
    image: "gradient-health",
    rating: 4.6,
    featured: false,
    contactPhone: "+44 20 7946 0020",
    contactEmail: "health@dzorwulupharmacy.co.uk",
    website: "https://dzorwulupharmacy.co.uk",
  },
];

export const jobsSeed = [
  {
    title: "Senior Software Developer",
    company: "TechGhana Ltd",
    location: "Shoreditch, London (Hybrid)",
    type: "Full-time",
    description:
      "Join our growing team to build innovative web and mobile applications. Work on exciting projects for clients across the UK and Ghana.",
    requirements: [
      "5+ years experience in React, Node.js, or Python",
      "Strong understanding of cloud services (AWS/GCP)",
      "Experience with agile development methodologies",
      "Excellent communication and teamwork skills",
    ],
    salary: "£65,000 - £85,000",
    postedDate: "2026-03-15",
    featured: true,
  },
  {
    title: "Immigration Solicitor",
    company: "Asante Legal Partners",
    location: "Tottenham, London",
    type: "Full-time",
    description:
      "Experienced immigration solicitor needed to join our busy practice. Handle visa applications, appeals, and citizenship cases for the Ghanaian community.",
    requirements: [
      "Qualified solicitor with 3+ years PQE in immigration law",
      "SRA accredited",
      "Experience with OISC Level 3 work",
      "Knowledge of Ghanaian documentation processes preferred",
    ],
    salary: "£50,000 - £70,000",
    postedDate: "2026-03-12",
    featured: true,
  },
  {
    title: "Head Chef",
    company: "Accra Kitchen",
    location: "Brixton, London",
    type: "Full-time",
    description:
      "Lead our kitchen team to deliver exceptional Ghanaian cuisine. Create new menu items while maintaining authentic traditional recipes.",
    requirements: [
      "Extensive experience in West African cuisine",
      "Food hygiene Level 3 certification",
      "Team management experience",
      "Passion for authentic Ghanaian flavours",
    ],
    salary: "£35,000 - £42,000",
    postedDate: "2026-03-10",
    featured: false,
  },
  {
    title: "Marketing Coordinator",
    company: "GoldCoast Express Logistics",
    location: "Croydon, London",
    type: "Full-time",
    description:
      "Drive our marketing efforts across digital and traditional channels. Grow brand awareness within the Ghanaian diaspora community in the UK.",
    requirements: [
      "2+ years marketing experience",
      "Strong social media management skills",
      "Experience with email marketing platforms",
      "Understanding of the Ghanaian diaspora market",
    ],
    salary: "£30,000 - £38,000",
    postedDate: "2026-03-08",
    featured: false,
  },
  {
    title: "Accountant",
    company: "Adinkra Financial Services",
    location: "Stratford, London",
    type: "Full-time",
    description:
      "Manage client accounts and provide financial advisory services. Specialise in cross-border tax planning for UK-Ghana dual residents.",
    requirements: [
      "ACCA or ACA qualified",
      "Experience with UK and international tax",
      "Knowledge of Ghana Revenue Authority regulations a plus",
      "Strong client relationship skills",
    ],
    salary: "£45,000 - £55,000",
    postedDate: "2026-03-05",
    featured: true,
  },
  {
    title: "Freelance Videographer",
    company: "Koforidua Media Group",
    location: "Camden, London (Remote/On-location)",
    type: "Freelance",
    description:
      "Create compelling video content for our diverse client base. Cover events, produce promotional videos, and edit social media content.",
    requirements: [
      "Professional videography portfolio",
      "Proficiency in Adobe Premiere Pro or Final Cut",
      "Own camera equipment preferred",
      "Available for weekend event coverage",
    ],
    salary: "£200 - £400 per day",
    postedDate: "2026-03-03",
    featured: false,
  },
  {
    title: "Part-time Sales Assistant",
    company: "Osu Market Foods",
    location: "Dalston, London",
    type: "Part-time",
    description:
      "Join our friendly team at Dalston's favourite Ghanaian grocery store. Help customers, manage stock, and maintain a welcoming shop environment.",
    requirements: [
      "Customer service experience",
      "Knowledge of Ghanaian food products preferred",
      "Flexible availability including weekends",
      "Ability to speak Twi or Ga is a bonus",
    ],
    salary: "£11.50 per hour",
    postedDate: "2026-03-01",
    featured: false,
  },
  {
    title: "Event Coordinator",
    company: "Labadi Events & Decor",
    location: "Edmonton, London",
    type: "Full-time",
    description:
      "Plan and coordinate weddings, naming ceremonies, and cultural events. Manage client relationships and vendor partnerships.",
    requirements: [
      "2+ years event planning experience",
      "Strong organisational and multitasking skills",
      "Knowledge of Ghanaian cultural traditions",
      "Valid UK driving licence",
    ],
    salary: "£28,000 - £35,000",
    postedDate: "2026-02-28",
    featured: false,
  },
  {
    title: "Web Developer Intern",
    company: "TechGhana Ltd",
    location: "Shoreditch, London",
    type: "Internship",
    description:
      "6-month paid internship for aspiring web developers from the Ghanaian community. Gain hands-on experience with modern web technologies.",
    requirements: [
      "Basic knowledge of HTML, CSS, and JavaScript",
      "Currently studying or recently graduated in a relevant field",
      "Eagerness to learn and grow",
      "Right to work in the UK",
    ],
    salary: "£22,000 (pro-rata)",
    postedDate: "2026-02-25",
    featured: false,
  },
  {
    title: "Delivery Driver",
    company: "GoldCoast Express Logistics",
    location: "Croydon, London",
    type: "Full-time",
    description:
      "Join our delivery team transporting parcels across London and the South East. Reliable drivers needed for our growing shipping service.",
    requirements: [
      "Full UK driving licence (Category B minimum)",
      "Clean driving record",
      "Knowledge of London roads",
      "Ability to lift parcels up to 25kg",
    ],
    salary: "£26,000 - £32,000",
    postedDate: "2026-02-20",
    featured: false,
  },
];

export const eventsSeed = [
  {
    title: "Ghana Independence Day Gala",
    description:
      "Celebrate Ghana's independence with an evening of music, dance, and fine dining. Featuring live highlife music, traditional drumming, and a keynote speech on the future of Ghana-UK relations.",
    date: "2026-03-06",
    time: "19:00",
    location: "The Grand Hall, Brixton, London",
    organizer: "Ghana High Commission UK",
    image: "gradient-event",
    category: "Cultural",
  },
  {
    title: "Ghanaian Business Networking Evening",
    description:
      "Connect with fellow Ghanaian entrepreneurs and professionals. Share ideas, forge partnerships, and grow your business network in the UK.",
    date: "2026-04-10",
    time: "18:30",
    location: "WeWork Moorgate, London",
    organizer: "GhanaConnect Community",
    image: "gradient-event",
    category: "Networking",
  },
  {
    title: "Financial Literacy Workshop",
    description:
      "Free workshop on managing finances across borders. Topics include UK tax obligations, sending money to Ghana, property investment, and pension planning.",
    date: "2026-04-18",
    time: "10:00",
    location: "Stratford Community Centre, London",
    organizer: "Adinkra Financial Services",
    image: "gradient-event",
    category: "Education",
  },
  {
    title: "Ghana Food Festival",
    description:
      "A weekend celebration of Ghanaian cuisine. Enjoy jollof rice cook-offs, street food stalls, cooking demonstrations, and live entertainment for the whole family.",
    date: "2026-05-16",
    time: "11:00",
    location: "Burgess Park, Peckham, London",
    organizer: "Accra Kitchen & Osu Market Foods",
    image: "gradient-event",
    category: "Food",
  },
  {
    title: "Tech Careers for Young Ghanaians",
    description:
      "Inspiring the next generation of Ghanaian tech talent. Panel discussions, CV workshops, and mentoring sessions with successful Ghanaian tech professionals in the UK.",
    date: "2026-05-30",
    time: "14:00",
    location: "TechGhana HQ, Shoreditch, London",
    organizer: "TechGhana Ltd & Sankofa Education Hub",
    image: "gradient-event",
    category: "Technology",
  },
];

export const categoriesSeed = [
  {
    name: "Food & Drink",
    icon: "UtensilsCrossed",
    type: "business",
    count: 4,
  },
  {
    name: "Legal",
    icon: "Scale",
    type: "business",
    count: 1,
  },
  {
    name: "Beauty",
    icon: "Scissors",
    type: "business",
    count: 3,
  },
  {
    name: "Transport",
    icon: "Truck",
    type: "business",
    count: 3,
  },
  {
    name: "Finance",
    icon: "PiggyBank",
    type: "business",
    count: 3,
  },
  {
    name: "Technology",
    icon: "Monitor",
    type: "business",
    count: 2,
  },
  {
    name: "Health",
    icon: "Heart",
    type: "business",
    count: 3,
  },
  {
    name: "Education",
    icon: "GraduationCap",
    type: "business",
    count: 1,
  },
];
